In [22]:
import numpy as np
a = np.arange(10)
a[10:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [48]:
n = 10
a = np.array(range(n))
p = a[::-1]
p

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [61]:
n = 10
array_ = np.array(range(n+1))
array_range = a[::-1]
diagon_matrix = np.diag(p)
sum_diag = np.trace(e)
sum_diag

55

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [3]:
from numpy import linalg
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])
x= linalg.solve(a,b,)
x

array([ 0.46666667,  3.84444444, -5.55555556])

In [4]:
np.dot(a,x)

array([ 4., 12., -3.])

Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [66]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_Length = np.linalg.norm( next_user_stats )
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
my_list =[]
for i in users_stats:
    users_Length = np.linalg.norm( i )
    my_list.append(np.dot(i, next_user_stats ) / ( users_Length * next_user_Length ))
best_user = np.argmax(np.array(my_list))
best_user             
    

7